# Generated by Django 5.2.17 on 2026-08-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='organization',
            field=models.CharField(max_length=255),
        ),
    ]
